BEGIN TRANSACTION;
CREATE TABLE "SOP_TEST" (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NAME`	TEXT NOT NULL UNIQUE,
	`TYPE`	TEXT,
	`CREATED`	TEXT,
	`USER`	TEXT
);
CREATE TABLE "SOP_RUN_QUERY" (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`CREATED`	TEXT,
	`RUN_ID`	INTEGER NOT NULL,
	`QUERY_ID`	INTEGER NOT NULL,
	`RESULTS_COUNT`	INTEGER
);
CREATE TABLE "SOP_RUN" (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`CREATED`	TEXT,
	`TEST_ID`	INTEGER NOT NULL,
	`TYPE`	INTEGER
);
CREATE TABLE "SOP_QUERY" (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`QUERY_TEXT`	TEXT,
	`TEST_ID`	INTEGER,
	`POSITION`	INTEGER,
	`QUERY_TYPE`	INTEGER
);
CREATE TABLE "SOP_CAPTURED_TESTS_HISTORY" (
	`ID`	INTEGER NOT NULL UNIQUE,
	`StartTimestamp`	INTEGER NOT NULL,
	`EndTimestamp`	INTEGER NOT NULL,
	`GraphNodeID`	INTEGER
);
COMMIT;
