sophia_neo4j:
  build: ./docker/
  dockerfile: Dockerfile_neo4j
  container_name: sophia_neo4j
  environment:
   NEO4J_AUTH: none
  ports:
   - "7474:7474"
  volumes:
   - "$HOME/Sophia_data/neo4j:/data"

sophia_rabbitmq:
  build: ./docker/
  dockerfile: Dockerfile_rabbitMQ
  container_name: sophia_rabbitmq
  ports:
   - "5672:5672"
   - "15672:15672"

sophia_app:
  build: .
  dockerfile: ./docker/Dockerfile_sophia_node_js
  container_name: sophia_app
  env_file: ./docker/http.env
  environment:
   HTTP_PROXY: http://web-proxy.il.hpecorp.net:8080
   NODE_ENV: production
   NEO4J_DB_SERVER: sophia_neo4j
  ports:
   - "8085:8085"
  working_dir: /Sophia
  command: node sophia_app.js
  links:
   - sophia_neo4j
  volumes:
   - "$HOME/Sophia_data/db:/Sophia/db"

sophia_data_server:
  build: .
  dockerfile: ./docker/Dockerfile_sophia_node_js
  container_name: sophia_data_server
  env_file: ./docker/http.env
  environment:
   NODE_ENV: development
   QUEUE_HOST: sophia_rabbitmq
   NEO4J_DB_SERVER: sophia_neo4j
  ports:
   - "8082:8082"
  working_dir: /Sophia
  command: node sophia_data_server.js
  links:
   - sophia_rabbitmq

sophia_file_server:
  build: .
  dockerfile: ./docker/Dockerfile_sophia_node_js
  container_name: sophia_file_server
  env_file: ./docker/http.env
  environment:
   NODE_ENV: development
   QUEUE_HOST: sophia_rabbitmq
  ports:
   - "8083:8083"
  working_dir: /Sophia
  command: node sophia_file_server.js
  links:
   - sophia_rabbitmq

sophia_queue_server:
  build: .
  env_file: ./docker/http.env
  dockerfile: ./docker/Dockerfile_sophia_node_js
  container_name: sophia_queue_server
  environment:
   NODE_ENV: development
   QUEUE_HOST: sophia_rabbitmq
   NEO4J_DB_SERVER: sophia_neo4j
  working_dir: /Sophia
  command: node sophia_queue.js
  links:
   - sophia_neo4j
   - sophia_rabbitmq
  volumes:
   - "$HOME/Sophia_data/db:/Sophia/db"

sophia_indexer_server:
  build: .
  dockerfile: ./docker/Dockerfile_sophia_node_js
  container_name: sophia_indexer_server
  env_file: ./docker/http.env
  environment:
   NODE_ENV: development
   QUEUE_HOST: sophia_rabbitmq
   NEO4J_DB_SERVER: sophia_neo4j
  working_dir: /Sophia
  command: node sophia_indexer.js
  links:
   - sophia_neo4j
   - sophia_rabbitmq