# base image
FROM node:5.3-slim

# proxy env
# ENV HTTP_PROXY=$HTTP_PROXY \
#	HTTPS_PROXY=$HTTPS_PROXY \
#	http_proxy=$HTTP_PROXY \
#	https_proxy=$HTTPS_PROXY

# make sure all dependencies are installed
# define npm http proxy
COPY package.json /Sophia/
RUN cd Sophia && \
	npm config set proxy http://web-proxy.il.hpecorp.net:8080 && \
	npm config set http-proxy http://web-proxy.il.hpecorp.net:8080 && \
	npm config set https-proxy https://web-proxy.il.hpecorp.net:8080 && \
	npm config set registry http://registry.npmjs.org/ && \
	npm install

# copy the sophia code
COPY . /Sophia/