# base image
FROM node:5.3-slim

# proxy env
ENV HTTP_PROXY $HTTP_PROXY
ENV HTTPS_PROXY $HTTPS_PROXY
ENV http_proxy $HTTP_PROXY
ENV https_proxy $HTTPS_PROXY

# make sure all dependencies are installed
COPY package.json /sophia/
RUN cd sophia && npm install

# expose the port for the sophia_data_server
ARG SOPHIA_DATA_SERVER_PORT
EXPOSE ${SOPHIA_DATA_SERVER_PORT:-8082}

# start the data server
COPY . /sophia/
ENTRYPOINT ["node", "sophia_data_server.js"]